### ISSUE TITLE
Implement return type undefined for Ethereum getAccount

### ISSUE THREAD

**Issue by LucasIsasmendi** [iov-one/iov-core#768] opened 2019-02-13 18:03 UTC
Currently, `ethereumconnection.getAccount` always return `Account` type data, while others return `undefined` when there is no account information in the blockchain.

One way to fix this issue is if `eth_getBalance` returns `0x0`, then check if account exists in scrapper with `searchTx` by address, and if it returns empty array, then `getAccount` should return `undefined`

**Comment by webmaster128** [comment] 2019-02-23 19:53
Duplicate of https://github.com/iov-one/iov-core/issues/676. Moving this up in priority now

**Closed by webmaster128** 2019-02-23 19:53 UTC
